# Netlify Configuration for SkillSync Beta
# Project ID: a6885992-2f64-4b46-911b-926f82fc7ae3

[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps"

# Next.js Runtime Plugin (handles SSR, ISR, API routes)
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security Headers (Best Practice)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets (Best Practice)
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for clean URLs (Best Practice)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 404 handling
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
